version: "3"


services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongo-db
  mongo-db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
